version: '3'

services:
  postgres_db:
    image: postgres:latest
    container_name: Postgres
    restart: always
    volumes:
      #- ./01-country.sql:/docker-entrypoint-initdb.d/01-country.sql
      #- ./02-gdp.sql:/docker-entrypoint-initdb.d/02-gdp.sql
      #- ~/apps/postgres:/var/lib/postgresql/data
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=world_bank_api
    ports:
      - "5432:5432"
volumes:
  postgres_db:
    driver: local